### ISSUE TITLE
Use Fira Mono as header font

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#1]
**Steps to complete**

1. Download [Fira Mono](http://google-webfonts-helper.herokuapp.com/fonts/fira-mono?subsets=latin) 700 weight
2. Add a 'fonts' folder inside the assets folder
3. Move the Fira Mono woff and woff2 files into the fonts folder
4. Import the fonts using @font-face at the top of the style.css file. Example:
```css
@font-face {
  font-family: FontName;
  src: url('path/filename.woff2') format('woff2'), 
    url('path/filename.woff') format('woff');
}
```
5. Add Fira Mono to the beginning of the headers font-family property. Example:
```css
h1,
h2,
h3,
h4,
h5,
h6 {
	font-family: 'Fira Mono', 'Courier New', Courier, monospace;
}
```
