### ISSUE TITLE
Use a sans-serif font in the body

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#2]
Let's update the global font-family to a sans serif font. It can either be a default font or a locally hosted font. If using a locally hosted font, please refer to #1 for details on folder structure and `@font-face`

Code to be updated
```css
body {
	font-family: 'Courier New', Courier, monospace;
}
```
