### ISSUE TITLE
Update font path

### ISSUE THREAD

**Issue by stormcloud266** [stormcloud266/web-dev-playground#5]
The `@font-face` is currently using the example path. Let's adjust this to use the real path to the fonts. Code to be updated in the style.css file: 

```css
@font-face {
	font-family: FontName;
	src: url('path/filename.woff2') format('woff2'), 
	  url('path/filename.woff') format('woff');
  }
```
